enum ReturnType {
	WORK_FINE,
	HDCP_INNER_PARAM_KEY_QUANTITY_ERROR,
	HDCP_INNER_PARAM_KEY_RANGE_ERROR,
	HDCP_INNER_KEY_OP_ERROR,
	HDCP_INNER_PARAM_FILE_OPEN_ERROR,
	HDCP_PARAM_KEY_HEADLEN_ERROR,
	HDCP_PARAM_KEY_HEADF_ERROR,
	HDCP_PARAM_KEY_KEYLENHEADF_ERROR,
	HDCP_PARAM_KEY_KEYLOC_ERROR,
	HDCP_PARAM_KEY_KEYLEN_ERROR,
	HDCP_PARAM_KEY_RANGESET_ERROR,
	HDCP_PARAM_FILE_OPEN_ERROR,

	MANAGER_PARAM_FILE_OPEN_ERROR,
	MANAGER_PARAM_KEY_TYPE_ERROR,
	MANAGER_PARAM_KEY_RANGESET_ERROR,
};